name: Build APK

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build type"
        required: false
        default: "release"
        type: choice
        options:
          - release
          - debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          if [ "${{ inputs.build_type }}" = "debug" ]; then
            flutter build apk --debug
          else
            flutter build apk --release
          fi

      - name: Find APK
        run: |
          echo "APK hasil build:"
          find build/app/outputs/flutter-apk -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ inputs.build_type }}
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
